export const proyectos = [
  {
    _id: 0,
    cover: "/images/img-1.jpg",
    images: [
      "/projects/braza_01.webp",
      "/projects/braza_02.webp",
      "/projects/braza_03.webp",
      "/projects/braza_04.webp",
      "/projects/braza_05.webp",
      "/projects/braza_06.webp",
      "/projects/braza_07.webp",
      "/projects/braza_08.webp",
    ],
    videos: [],
    color: ["#531B0C", "#FD8963"],
    name: "BRAZZA GRILL HOUSE",
    paragraphs: [
      "A través de nuestras sesiones fotográficas, hemos dado vida a cada plato con imágenes que despiertan el apetito de los clientes, siguiendo al pie de la letra lo que nuestro socio nos solicitó. ",
      "Usando el equipo requerido como cámaras de la más alta calidad, luces especializadas, y el uso de modelos. Dedicamos el tiempo requerido a cada toma logrando sacar lo mejor de cada platillo.",
      "Además, hemos diseñado un menú que no solo es visualmente atractivo, sino también intuitivo y fácil de navegar con nuestros códigos QR. Nuestro diseño destaca lo mejor de su oferta culinaria, creando una identidad de marca única en su estilo.Usando el equipo requerido como cámaras de la más alta calidad, luces especializadas, y el uso de modelos. Dedicamos el tiempo requerido a cada toma logrando sacar lo mejor de cada platillo.Además, hemos diseñado un menú que no solo es visualmente atractivo, sino también intuitivo y fácil de navegar con nuestros códigos QR. Nuestro diseño destaca lo mejor de su oferta culinaria, creando una identidad de marca única en su estilo.",
    ],
  },
  {
    _id: 1,
    cover: "/images/img-2.jpg",
    images: [
      "/projects/super24_01.webp",
      "/projects/super24_02.webp",
      "/projects/super24_03.webp",
      "/projects/super24_04.webp",
      "/projects/super24_05.webp",
      "/projects/super24_06.webp",
      "/projects/super24_07.webp",
      "/projects/super24_08.webp",
      "/projects/super24_09.webp",
      "/projects/super24_010.webp",
      "/projects/super24_011.webp",
      "/projects/super24_012.webp",
      "/projects/super24_013.webp",
      "/projects/super24_014.webp",
      "/projects/super24_015.webp",
      "/projects/super24_016.webp",
      "/projects/super24_017.webp",
      "/projects/super24_018.webp",
      "/projects/super24_019.webp",
      "/projects/super24_020.webp",
      "/projects/super24_021.webp",
      "/projects/super24_022.webp",
      "/projects/super24_023.webp",
      "/projects/super24_024.webp",
      "/projects/super24_025.webp",
    ],
    videos: [],
    color: ["#00235C", "#FD673D"],
    name: "SUPER 24",
    paragraphs: [
      "Mediante la implementación de grabaciones profesionales, fotografías creativas, y reels dinámicos en Instagram, hemos fortalecido la presencia de SUPER 24 en redes sociales.",
      "Nuestro enfoque se ha basado en el uso estratégico de equipos de alta gama, la creatividad de nuestros editores y profesionales, así como la selección estratégica de modelos.",
      "Estas acciones han potenciado significativamente la marca, generando un impacto positivo notable en las ventas.",
    ],
  },
  {
    _id: 2,
    cover: "/images/img-3.jpg",
    images: ["/projects/cloe_01.webp", "/projects/cloe_02.webp"],
    videos: [],
    color: ["#501B53", "#973274"],
    name: "CLOE MTV",
    paragraphs: [
      "En colaboración con la marca de bolsas y accesorios CLOE X MTV, desarrollamos una campaña creativa para expandir la presencia de CLOE en el mercado juvenil Internacional, publicidad que se presentó en los aeropuertos.",
      "Utilizando nuestro equipo profesional de cámaras fotográficas, de video e iluminación hemos creado contenido visual que fusiona el estilo audaz de CLOE con la cultura pop representada por MTV.",
      "Desde la concepción hasta la ejecución, nos hemos encargado de la creatividad de sesiones de fotos para después ser producidas. Nuestra experiencia en edición de video y fotografía ha garantizado que cada pieza comunicativa refleje la identidad vibrante de ambas marcas.",
    ],
  },
  {
    _id: 3,
    cover: "/images/img-4.jpg",
    images: [
      "/projects/la_cochera_01.webp",
      "/projects/la_cochera_02.webp",
      "/projects/la_cochera_03.webp",
      "/projects/la_cochera_04.webp",
      "/projects/la_cochera_05.webp",
      "/projects/la_cochera_06.webp",
    ],
    videos: [],
    color: ["#53371F", "#FD9F77"],
    name: "LA COCHERA",
    paragraphs: [
      "Nos enorgullece presentar el proyecto La Cochera, donde hemos trabajado incansablemente para capturar la esencia única de sus productos y llevarlos al mundo digital.",
      "Con fotografías creadas en estudio, diseñamos un menú interactivo específicamente para las 12 sucursales, donde se proyectaron en pantallas dentro de los establecimientos permitiendo a los clientes explorar y descubrir cada detalle del producto.",
    ],
  },
  {
    _id: 4,
    cover: "/images/img-5.jpg",
    images: [
      "/projects/politica_01.webp",
      "/projects/politica_02.webp",
      "/projects/politica_03.webp",
      "/projects/politica_04.webp",
    ],
    videos: ["/projects/politica_05.webm"],
    color: ["#FD673D", "#DBC200"],
    name: "POLÍTICA",
    paragraphs: [
      "Nos especializamos en marketing ATL (above the line) y BTL (below the line) para clientes del ámbito político. Nuestros servicios abarcan desde el diseño de espectaculares y volantes hasta la creación de guiones y edición de videos, así como la producción de audios para perifoneo de campaña.",
      "Gracias a nuestra labor integral, logramos aumentar significativamente la visibilidad y llevar al triunfo a nuestros candidatos, capturando autenticidad y esencia de manera impactante mediante estrategias publicitarias y un equipo especializado en fotografía, video y estrategia.",
    ],
  },
];
